export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

//SHIPPING

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS"

//PAYMENT

export const SAVE_PAYMENT = "SAVE_PAYMENT"
